name: CI

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      # - name: Build and test
      #   run: ./gradlew build --build-cache --console=plain --scan

      - name: Log in to Container registry
        # if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test
        run: |
          ./gradlew build -Dquarkus.container-image.build=true \
              --build-cache --console=plain --scan

      - name: Push Docker image
        run: |
          ./gradlew build -Dquarkus.container-image.push=true \
              --build-cache --console=plain --scan

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          include_passed: true
          detailed_summary: true

      # - name: Log in to Container registry
      #   # if: github.ref == 'refs/heads/main'
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build native binary
      #   # if: github.ref == 'refs/heads/main'
      #   run: |
      #     ./gradlew build -Dquarkus.native.enabled=true \
      #         -Dquarkus.package.jar.enabled=false \
      #         -Dquarkus.native.container-build=true \
      #         -Dquarkus.container-image.build=true \
      #         -Dquarkus.container-image.push=true \
      #         --build-cache --console=plain --scan

      # - name: debug
      #   run: ls -lah build

      # - name: Build Docker image
      #   # if: github.ref == 'refs/heads/main'
      #   run: |
      #     ./gradlew build -Dquarkus.container-image.build=true

      # - name: Push Docker image
      #   # if: github.ref == 'refs/heads/main'
      #   run: |
      #     ./gradlew build -Dquarkus.container-image.push=true --build-cache --console=plain --scan
